version: '3.8'

services:
  mongo-phishvault:
    image: mongo:6
    container_name: mongo-phishvault
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: phishvault-backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo-phishvault:27017
      - PORT=4000
    depends_on:
      - mongo-phishvault

volumes:
  mongo_data: